### ISSUE TITLE
ERROR: java.lang.NoClassDefFoundException on Windows

### ISSUE THREAD

**Issue by michelou** [hpi-swa/graalsqueak#72]
Environment setup:
1) `C:\opt\graalvm-ce-19.2.0.1\` ([Github](https://github.com/oracle/graal/releases/tag/vm-19.2.0.1))
2) Manual installation of `graalsqueak-component-1.0.0-rc3-for-GraalVM-19.2.0.1.jar` ([Github](https://github.com/hpi-swa/graalsqueak/releases/tag/1.0.0-rc3))
3) Manual addition of Windows script `jre\languages\smalltalk\bin\graalsqueak.cmd` adapted from `jre\languages\smalltalk\bin\graalsqueak` (see PR ???).
4) `C:\opt\Squeak-5.2\` ([Download Site](https://squeak.org/downloads/))

Session with **error message**:
```
$ c:\opt\graalvm-ce-19.2.0.1\jre\languages\smalltalk\bin\graalsqueak.cmd c:\Squeak-5.2\Squeak5.2-18229-64bit.image
[graalsqueak] Running Squeak/Smalltalk on OpenJDK 64-Bit GraalVM CE 19.2.0.1 (Graal-compiled)...
ERROR: java.lang.NoClassDefFoundError: com/sun/security/auth/module/UnixSystem
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/sun/security/auth/module/UnixSystem
        at de.hpi.swa.graal.squeak.nodes.plugins.UnixOSProcessPlugin.<clinit>(UnixOSProcessPlugin.java:35)
        at de.hpi.swa.graal.squeak.nodes.primitives.PrimitiveNodeFactory.initialize(PrimitiveNodeFactory.java:89)
        at de.hpi.swa.graal.squeak.image.SqueakImageContext.initializePrimitives(SqueakImageContext.java:348)
        at de.hpi.swa.graal.squeak.image.reading.SqueakImageReader.run(SqueakImageReader.java:94)
        [...]
        at de.hpi.swa.graal.squeak.launcher.GraalSqueakLauncher.main(GraalSqueakLauncher.java:55)
Caused by: java.lang.ClassNotFoundException: com.sun.security.auth.module.UnixSystem
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 19 more
```

**Comment by michelou** [comment]
Issue fixed with commit [0741afd]
